### ISSUE TITLE
Выложить исходники блок-схем

### ISSUE THREAD

**Issue by tormozit** [kuzyara/Sequences-of-events-for-1C-objects#2]
Думаю было бы полезно выложить и исходники блок-схем с указанием программы-редактора соответствующего формата.

**Comment by kuzyara** [comment]
https://app.diagrams.net/?mode=github#Hkuzyara%2FSequences-of-events-for-1C-objects%2Fmaster%2FFormSeqDiagram.drawio

**Comment by kuzyara** [comment]
обновил ридми, остальные в пэйнте рисовал)
